### ISSUE TITLE
Resources not loaded properly when refreshing after scrolling

### ISSUE THREAD

**Issue by captainsafia** [nteract/nteract.github.io#5]
Following up on what @Carreau opened on #4. If you scroll down the page and then refresh, you get the following.

Buttons and logo are awkward.

![screen shot 2016-06-07 at 9 56 28 pm](https://cloud.githubusercontent.com/assets/1857993/15881326/b7ebbb6e-2cfa-11e6-87d3-bfb3acd8469d.png)

**Comment by Carreau** [comment]
Still the case for me:


![screen shot 2016-06-08 at 10 25 03](https://cloud.githubusercontent.com/assets/335567/15903804/6236af3a-2d63-11e6-91e8-8b9837a62753.png)

**Comment by Carreau** [comment]
Or is it because the fix seem to not have been deployed ?

**Comment by aulneau** [comment]
@Carreau I had not deployed -- I wasn't sure if I should be the one deploying or not. I can right now.

**Comment by Carreau** [comment]
> @Carreau I had not deployed -- I wasn't sure if I should be the one deploying or not. I can right now.

I would just make a PR against master. Then once it's merge it will auto close the issue and deploy it to gh-pages.

**Comment by Carreau** [comment]
BTW I see that this repo as both a `master` and a `gh-pages` branch, IIUC the second one seem unnecessary as this is an org pages, and not a per-repo page.

**Comment by aulneau** [comment]
I think we will need a second branch to make a pull request against -- I don't think I can make a pull request from `landing-page` to `master` because `master` contains only the contents of the `/dist/` folder. I would love to know what you think would be the best way to automate the deployment process, @Carreau.

**Comment by Carreau** [comment]
Hum, if you use jekyll only, then gh-pages would build automatically it before deploying. 
If you need to run gulp or something else, you can use Travis-CI that would run only on gh-pages or similar and push back on master if test pass.

**Comment by Carreau** [comment]
I just enabled Travis, we could generate and encrypt an ssh-key then on after_success :
```
#!/bin/bash

if [[ ( "$TRAVIS_BRANCH" == "gh-pages" ) && ( "$TRAVIS_PULL_REQUEST" == 'false' ) && ( "$TRAVIS_REPO_SLUG" == "nteract/nteract.github.io" ) ]] ;
then
  echo 'deploying site'
  gulp whatever

  # decrypt  credential for github. 
  echo 'Decrypting ssh key ...'
  openssl aes-256-cbc -K $encrypted_669152acb59a_key -iv $encrypted_669152acb59a_iv -in .id_rsa.enc -out ~/.shh/id_rsa -d
  git push whatever on master
else
  echo 'Not master, not nteract website repo, or in a pull request: doing nothing.'
fi
```

But I think you are right that we might have to close issues manually. Unless we have the website on a separate repo. 

That what we do for https://github.com/ipython/ipython-website which deploy on https://github.com/ipython/ipython.github.com

**Comment by captainsafia** [comment]
@Carreau: I'm a little confused by what this is trying to do. Do we need Travis to build the site? Could we just use a `post-recieve` hook to compile with gulp?

Also, could we set up SSL on Cloudflare?

**Comment by Carreau** [comment]
> just use a post-recieve hook to compile with gulp

No because you can't have a post-receive on github. Unless you achieve to ssh to github and install a post-receive. So you need to build before pushing to github. The master branch have to be the final html version. 

Sidenote, github git tree is not stored on a filesystem, it uses in memory DB. so you can't run a post receive hook. 

hence you : 
  - push on github on branch B, 
  - travis get triggered, clone the website, build it, 
  - push on branch A, 
  - Branch A is displayed on gh-pages. 

Does that make sens ?

**Comment by captainsafia** [comment]
OK. So a .travis.yml script needs to be added to the dev branch with the script above?

**Comment by Carreau** [comment]
Probably. You can also (likely) inline the script in the travis.yml, but since @aulneau  made https://github.com/nteract/nteract.github.io/pull/7 that will be even simpler. THe only hard things is to genereate tokens, and encrypt them for travis to be able to push back.
